//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 05:25:13 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengroup.org/xsd/omi/1.0/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xsd.omi;
